name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Create repo .npmrc
        run: echo "${{ secrets.DOT_NPMRC }}" > .npmrc 

      - name: Fail early if .npmrc missing
        run: |
          if [ ! -f .npmrc ]; then
            echo "ERROR: < .npmrc > does not exist"
            exit 1
          fi

      - name: Explicitly set registry
        run: npm config set registry https://registry.npmjs.org

      - name: Diagnostics .npmrc
        run: |
          echo -n "Last six of auth: "
          tail -c 6 .npmrc

      - name: Get registry
        run: npm config get registry

      - name: Check npm whoami
        run: npm whoami || true

      - name: Install dependencies
        run: npm ci

      - name: Create eslint config
        run: |
          let EC="eslint.config.js"
          echo 'import js from "@eslint/js";' > ${EC}
          echo 'import globals from "globals";' >> ${EC}
          echo 'import css from "@eslint/css";' >> ${EC}
          echo 'import { defineConfig } from "eslint/config";' >> ${EC}
          echo 'export default defineConfig([' >> ${EC}
          echo '  {' >> ${EC} 
          echo '    files: ["**/*.{js,mjs,cjs}"],' >> ${EC} 
          echo '    plugins: { js },' >> ${EC} 
          echo '    extends: ["js/recommended"],' >> ${EC} 
          echo '    languageOptions: { globals: globals.browser }' >> ${EC} 
          echo '  },' > ${EC}
          echo '  {' > ${EC} 
          echo '    files: ["**/*.css"],' > ${EC} 
          echo '    plugins: { css },' > ${EC} 
          echo '    language: "css/css",' > ${EC} 
          echo '    extends: ["css/recommended"]' > ${EC} 
          echo '  },' > ${EC}
          echo ']);' > ${EC}

      - name: Verify eslint config
        run: cat eslint.config.js

      - name: Run build
        run: npm run build

      - name: Double-check npm whoami
        run: npm whoami || true

      - name: Diagnostics npm config registry and whoami
        run: |
          echo -n "Last six of auth: "
          tail -c 6 .npmrc

      - name: Dry-run publish (shows what would be published)
        run: npm publish --dry-run --access public

      - name: Publish to npm (final)
        run: npm publish --access public || true
