name: Publish debug - show masked token and whoami

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if NPM_TOKEN missing
        if: ${{ secrets.NPM_TOKEN == '' }}
        run: |
          echo "ERROR: NPM_TOKEN is not set as a repository secret."
          exit 1

      - name: Write token to ~/.npmrc (hidden)
        run: |
          printf "//registry.npmjs.org/:_authToken=%s\n" "${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          chmod 600 ~/.npmrc
          echo ".npmrc written"

      - name: Show masked token and registry and whoami
        run: |
          echo "registry: $(npm config get registry)"
          echo "masked token (last 6 chars):"
          awk -F= '{tok=$2; gsub(/^[[:space:]]+|[[:space:]]+$/,"",tok); if(length(tok)>6){printf "%s=***%s\n",$1,substr(tok,length(tok)-5)} else {print $0}}' ~/.npmrc || true
          echo "npm whoami:"
          npm whoami || true
