name: Publish to npm
on:
  # Trigger on push to main and allow manual runs
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'                     # pick your Node version
          registry-url: 'https://registry.npmjs.org/'
          node-auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build # if you have a build step

      - name: Publish to npm
        run: npm publish --access public        # use --access public for scoped public packages
