name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Create repo .npmrc
        run: echo "${{ secrets.DOT_NPMRC }}" > .npmrc 

      - name: Fail early if .npmrc missing
        run: |
          if [ ! -f .npmrc ]; then
            echo "ERROR: < .npmrc > does not exist"
            exit 1
          fi

      - name: Explicitly set registry
        run: npm config set registry https://registry.npmjs.org

      - name: Check npm whoami
        run: npm whoami || true

      - name: Install dependencies
        run: npm ci

      - name: Create eslint config
        shell: bash
        run: |
          ec='eslint.config.js'
          echo 'import js from "@eslint/js";' > ${ec}
          echo 'import globals from "globals";' >> ${ec}
          echo 'import css from "@eslint/css";' >> ${ec}
          echo 'import { defineConfig } from "eslint/config";' >> ${ec}
          echo 'export default defineConfig([' >> ${ec}
          echo '  { ' >> ${ec} 
          echo '    files: ["**/*.{js,mjs,cjs}"],' >> ${ec} 
          echo '    plugins: { js },' >> ${ec} 
          echo '    extends: ["js/recommended"],' >> ${ec} 
          echo '    languageOptions: { globals: globals.browser }' >> ${ec} 
          echo '  },' >> ${ec}
          echo '  { ' >> ${ec} 
          echo '    files: ["**/*.css"],' >> ${ec} 
          echo '    plugins: { css },' >> ${ec} 
          echo '    language: "css/css",' >> ${ec} 
          echo '    extends: ["css/recommended"]' >> ${ec} 
          echo '  },' >> ${ec}
          echo ']);' >> ${ec}

      - name: Run build
        run: npm run build

      - name: Check npm whoami
        run: |
          npm config get registry
          echo -n "Last six of auth: "
          tail -c 6 .npmrc
          npm whoami || true

      - name: Create .npmignore
        shell: bash
        run: |
          echo ".git*" > .npmignore
          echo "*.swp" >> .npmignore
          echo "*.url" >> .npmignore
          echo "test*" >> .npmignore
          echo ".npmrc" >> .npmignore
          echo "*.png" >> .npmignore
          echo "/node_modules" >> .npmignore
          echo "package-lock.json" >> .npmignore
          echo "eslint.config.js" >> .npmignore
          echo "index.html" >> .npmignore
          echo "*.svg" >> .npmignore

      - name: Verify .npmignore
        run: cat .npmignore

      - name: Publish to npm
        run: echo "npm publish --access public || true"
